
dict_ca_types= {"Corporate Action Status":"text",
                "If modification id":"numeric",
                "Corporate Action Date":"datetime",
                "Scope Affected":"text",
                "Identification":"text",
                "Corporate Action Effective Date":"datetime",
                "Corporate Action Receipt Date":"datetime",
                "Document":"text",
                "Dividend Announcement Date":"datetime",
                "Dividend Record Date":"datetime",
                "Dividend Ex Date":"datetime",
                "Dividend Payment Date":"datetime",
                "Dividend Gross":"numeric",
                "Dividend Net":"numeric",
                "How is the Dividend payed?":"text",
                "Portfolio Manager Name":"text",
                "Portfolio Manager Role Starting Date":"datetime",
                "ManCo":"text",
                "Domicile Of ManCo":"text",
                "Email address of the ManCo":"text",
                "Split Ratio":"numeric",
                "Reverse Split":"numeric",
                "Fund Advisor Name":"text",
                "Sub Investment Advisor Name":"text",
                "Fund Administrator Name":"text",
                "Custodian Bank Name":"text",
                "Depositary Bank Name":"text",
                "Depositary Bank LEI":"text",
                "Transfer Agent Name":"text",
                "LEI of Custodian":"text",
                "Auditor Name":"text",
                "Umbrella":"text",
                "Domicile of Umbrella":"text",
                "Legal Fund Name Including Umbrella":"text",
                "Legal Fund Name Only":"text",
                "Fund Launch Date":"datetime",
                "Full Share Class Name":"text",
                "Abbreviated Share Class Name":"text",
                "NAV publication incidents":"text",
                "Share Class Lifecycle":"text",
                "Dormant Start Date":"datetime",
                "Dormant End Date":"datetime",
                "Liquidation Start Date":"datetime",
                "Termination Date":"datetime",
                "Investment Status":"text",
                "Min Initial Subscription in Shares":"numeric",
                "Min Initial Subscription in Amount":"numeric",
                "Currency of Min Subscription":"text",
                "Min Subsequent Subscription in Shares":"numeric",
                "Min Subsequent Subscription in Amount":"numeric",
                "Min Redepmtion Category":"text",
                "Min Initial Redepmtion in Shares":"numeric",
                "Min Initial Redepmtion in Amount":"numeric",
                "Currency of Minimum Redemption":"text",
                "Standard Min Remaing Amount":"numeric",
                "Currency of Min Remaining Amount":"text",
                "Performance Fee Applied":"text",
                "Custodian Fee Applied":"text",
                "Depositary Fee Applied":"text",
                "Applied Subscription Fee In Favour of Fund":"text",
                "Applied Subscription Fee In Favour of Distributor":"text",
                "Applied Redepmtion Fee in Favour of Distributor":"text",
                "Applied Redepmtion Fee in Favour of Fund":"text",
                "Management Fee Applied":"text",
                "All in Fee Applied":"text",
                "Distribution Fee":"text",
                "Ongoing Charges":"text",
                "Servicing Fees":"text",
                "Conversion Fee":"text",
                "Subscription Fee Max":"text",
                "Redemption Fee Max":"text",
                "Redemption Notice Period":"text",
                "Fund Valuation Point":"text",
                "Valuation Frequency":"text",
                "Max Number of Possible Decimals Shares":"text",
                "Max Number of Possible Decimals Amounts":"text",
                "Max Number of Possible Decimals NAV":"text",
                "Cut off time for Subscription":"text",
                "Cut off time":"text",
                "Calendar or business days for transactions":"text",
                "Settlement Period for Subscription":"text",
                "Settlement Period for Redemption":"text",
                "Non Dealing Days":"text",
                "NAV Displacement days":"text",
                "Time Zone For Cut-off":"text",
                "General Meeting Points":"text",
                "General Meeting Date":"text",
                "Extraordinay general meeting date":"text",
                "Reply expected":"text",
                "ISIN_Merger_Fund_Absorbing":"text",
                "ISIN_Merged_Fund_absorbed":"text",
                "LEI Merge absorbed":"text",
                "LEI Merge absorbing":"text",
                "Last_trade_Date_absorbing Fund":"text",
                "Last_trade_Date_absorbed Fund":"text",
                "Last Day for redemption before Merge or Liquidation":"text",
                "MergerTaxExempt":"text",
                "Umbrella LEI Merge absorbing":"text",
                "Umbrella LEI Merge absorbed":"text",
                "Fund Guarantor":"text",
                "Guarantor Rating Review":"text",
                "Investment Objective":"text",
                "Max Leverage in Fund":"text",
                "Is Fund Targeting Environmental or Social Objectives (EOS)":"text",
                "Swap Counterparty Name":"text",
                "Investment Policy":"text",
                "Free Text":"text",
                "Is Eligible for tax deferred Fund switch in Spain":"text",
                "Number of Shareholders":"text",
                "PEA Plan dEpargne in actions":"text",
                "Other Tax Figures":"text",
                "NAV disclosed channel":"text" ,               
                "Country Registration":"text",
                "Country Deregistration":"text",
                "New KIID Date":"text",
                "New Prospectus Date":"text",
                "NewAnualReport":"text",
                "New Prospectus Supplement Date":"text",
                "New SemiAnnual Report Date":"text",
                "Business Day Calendar":"text",
                "Fund Leverage over 5%":"text",
                "De-listing of a Stock Exchange":"text",
                "Significant Asset reduction":"text",
                "Suspension of operations":"text",
                "Beat the pre-defined payoff":"text",
                "Partial Liquidation":"text",
                "EMT Client Type Retail":"text",
                "EMT Professional Investor Type":"text",
                "EMT Is Investor Type Eligible Counterparty":"text",
                "Total liquidation":"text",
                "Share Class Distribution Policy":"text",
                "EMT PRIIP Summary Risk Indicator":"text",
                "VAR Policy":"text",
                "Benchmark":"text",
                "Single Pricing Type":"text",
                "Anti Dilution measures":"text"}
