
dict_ca_name_n  =  {"Dividends": "1",
                    "Investment Manager": "2",
                    "Management Company": "3",
                    "Split and Reverse Split": "4",
                    "Advisor": "5",
                    "Admin Custodian Transfer Agent": "6",
                    "Auditor": "7",
                    "SICAV Static and Sub Fund Statics": "8",
                    "NAV Publications Incidents": "9",
                    "Investment Status": "10",
                    "Min Investment Amount or Min Holdings": "11",
                    "Fees": "12",
                    "Subscription Redemption Notice Periods": "13",
                    "Settlement Data": "14",
                    "General Meeting": "15",
                    "Mergers": "16",
                    "Guarantor": "17",
                    "Investment Policy": "18",
                    "Other Corporate Actions": "19",
                    "Taxation and Register": "20",
                    "Public Periodical Information":"21",
                    "CNMV C.A. defined":"22",
                    "Partial Liquidation":"23",
                    "Target Market":"24",
                    "Total Liquidation":"25",
                    "Distribution Policy":"26",
                    "Risk":"27",
                    "Benchmark Index":"28",
                    "Implementation Swing Price / Antidilution measures":"29"}
