
dict_div_rename = {"Dividends" : {"Corporate Action Status":"ficad00000",
                                  "If modification id":"fica000007",
                                  "Corporate Action Date":"ficad00001",
                                  "Scope Affected":"fica000001",
                                  "Identification":"fica000002",
                                  "Corporate Action Effective Date":"ficad00003",
                                  "Corporate Action Receipt Date":"fiad00004",
                                  "Document":"fica000005",
                                  "Dividend Announcement Date":"ofdy005005",
                                  "Dividend Record Date":"ofdy005007",
                                  "Dividend Ex Date":"ofdy005010",
                                  "Dividend Payment Date":"ofdy005015",
                                  "Dividend Gross":"ofdy005020",
                                  "Dividend Net":"ofdy005022",
                                  "How is the Dividend payed?":"fica003021"},
                    "Investment Manager" : {"Corporate Action Status":"ficad00000",
                                            "If modification id":"fica000007",
                                            "Corporate Action Date":"ficad00001",
                                            "Scope Affected":"fica000001",
                                            "Identification":"fica000002",
                                            "Corporate Action Effective Date":"ficad00003",
                                            "Corporate Action Receipt Date":"fiad00004",
                                            "Document":"fica000005",
                                            "Portfolio Manager Name":"OFPM000010",
                                            "Portfolio Manager Role Starting Date":"OFPM000120"},
                    "Management Company" : {"Corporate Action Status":"ficad00000",
                                            "If modification id":"fica000007",
                                            "Corporate Action Date":"ficad00001",
                                            "Scope Affected":"fica000001",
                                            "Identification":"fica000002",
                                            "Corporate Action Effective Date":"ficad00003",
                                            "Corporate Action Receipt Date":"fiad00004",
                                            "Document":"fica000005",
                                            "ManCo":"OFST001020",
                                            "Domicile Of ManCo":"OFST001035",
                                            "Email address of the ManCo":"OFST001021"},
                    "Split and Reverse Split" : {"Corporate Action Status":"ficad00000",
                                                 "If modification id":"fica000007",
                                                 "Corporate Action Date":"ficad00001",
                                                 "Scope Affected":"fica000001",
                                                 "Identification":"fica000002",
                                                 "Corporate Action Effective Date":"ficad00003",
                                                 "Corporate Action Receipt Date":"fiad00004",
                                                 "Document":"fica000005",
                                                 "Split Ratio":"OFDY005062",
                                                 "Reverse Split":"FICA001010"},
                    "Advisor" : {"Corporate Action Status":"ficad00000",
                                 "If modification id":"fica000007",
                                 "Corporate Action Date":"ficad00001",
                                 "Scope Affected":"fica000001",
                                 "Identification":"fica000002",
                                 "Corporate Action Effective Date":"ficad00003",
                                 "Corporate Action Receipt Date":"fiad00004",
                                 "Document":"fica000005",
                                 "Fund Advisor Name":"OFST001500",
                                 "Sub Investment Advisor Name":"OFST001510"},
                    "Admin Custodian Transfer Agent" : {"Corporate Action Status":"ficad00000",
                                                         "If modification id":"fica000007",
                                                         "Corporate Action Date":"ficad00001",
                                                         "Scope Affected":"fica000001",
                                                         "Identification":"fica000002",
                                                         "Corporate Action Effective Date":"ficad00003",
                                                         "Corporate Action Receipt Date":"fiad00004",
                                                         "Document":"fica000005",
                                                         "Fund Administrator Name":"OFST001300",
                                                         "Custodian Bank Name":"OFST001400",
                                                         "Depositary Bank Name":"FICA001400",
                                                         "Depositary Bank LEI":"FICA001420",
                                                         "Transfer Agent Name":"OFST002700",
                                                         "LEI of Custodian":"FICA001430"},
                    "Auditor":{"Corporate Action Status":"ficad00000",
                                "If modification id":"fica000007",
                                "Corporate Action Date":"ficad00001",
                                "Scope Affected":"fica000001",
                                "Identification":"fica000002",
                                "Corporate Action Effective Date":"ficad00003",
                                "Corporate Action Receipt Date":"fiad00004",
                                "Document":"fica000005",
                                "Auditor Name":"OFST001600"},
                    "SICAV Static and Sub Fund Statics":{"Corporate Action Status":"ficad00000",
                                                         "If modification id":"fica000007",
                                                         "Corporate Action Date":"ficad00001",
                                                         "Scope Affected":"fica000001",
                                                         "Identification":"fica000002",
                                                         "Corporate Action Effective Date":"ficad00003",
                                                         "Corporate Action Receipt Date":"fiad00004",
                                                         "Document":"fica000005",
                                                         "Umbrella":"OFST005010",
                                                         "Domicile of Umbrella":"OFST005015",
                                                         "Legal Fund Name Including Umbrella":"OFST010020",
                                                         "Legal Fund Name Only":"OFST010110",
                                                         "Fund Launch Date":"OFST010240",
                                                         "Full Share Class Name":"OFST020060",
                                                         "Abbreviated Share Class Name":"OFST020070"},
                    "NAV Publications Incidents":{"Corporate Action Status":"ficad00000",
                                                  "If modification id":"fica000007",
                                                  "Corporate Action Date":"ficad00001",
                                                  "Scope Affected":"fica000001",
                                                  "Identification":"fica000002",
                                                  "Corporate Action Effective Date":"ficad00003",
                                                  "Corporate Action Receipt Date":"fiad00004",
                                                  "Document":"fica000005",
                                                  "NAV publication incidents":"FICA006100"},
                    "Investment Status":{"Corporate Action Status":"ficad00000",
                                         "If modification id":"fica000007",
                                         "Corporate Action Date":"ficad00001",
                                         "Scope Affected":"fica000001",
                                         "Identification":"fica000002",
                                         "Corporate Action Effective Date":"ficad00003",
                                         "Corporate Action Receipt Date":"fiad00004",
                                         "Document":"fica000005",
                                         "Share Class Lifecycle":"OFST020545",
                                         "Dormant Start Date":"OFST020562",
                                         "Dormant End Date":"OFST020563",
                                         "Liquidation Start Date":"OFST020564",
                                         "Termination Date":"OFST020566",
                                         "Investment Status":"OFST023100"},
                    "Min Investment Amount or Min Holdings":{"Corporate Action Status":"ficad00000",
                                                             "If modification id":"fica000007",
                                                             "Corporate Action Date":"ficad00001",
                                                             "Scope Affected":"fica000001",
                                                             "Identification":"fica000002",
                                                             "Corporate Action Effective Date":"ficad00003",
                                                             "Corporate Action Receipt Date":"fiad00004",
                                                             "Document":"fica000005",
                                                             "Min Initial Subscription in Shares":"OFST400220",
                                                             "Min Initial Subscription in Amount":"OFST400230",
                                                             "Currency of Min Subscription":"OFST400240",
                                                             "Min Subsequent Subscription in Shares":"OFST400250",
                                                             "Min Subsequent Subscription in Amount":"OFST400260",
                                                             "Min Redepmtion Category":"OFST420200",
                                                             "Min Initial Redepmtion in Shares":"OFST420220",
                                                             "Min Initial Redepmtion in Amount":"OFST420230",
                                                             "Currency of Minimum Redemption":"OFST420240",
                                                             "Standard Min Remaing Amount":"OFST430300",
                                                             "Currency of Min Remaining Amount":"OFST430310"},
                    "Fees":{"Corporate Action Status":"ficad00000",
                            "If modification id":"fica000007",
                            "Corporate Action Date":"ficad00001",
                            "Scope Affected":"fica000001",
                            "Identification":"fica000002",
                            "Corporate Action Effective Date":"ficad00003",
                            "Corporate Action Receipt Date":"fiad00004",
                            "Document":"fica000005",
                            "Performance Fee Applied":"OFST451028",
                            "Custodian Fee Applied":"OFST451040",
                            "Depositary Fee Applied":"OFST451046",
                            "Applied Subscription Fee In Favour of Fund":"OFST451336",
                            "Applied Subscription Fee In Favour of Distributor":"OFST451305",
                            "Applied Redepmtion Fee in Favour of Distributor":"OFST451405",
                            "Applied Redepmtion Fee in Favour of Fund":"OFST451436",
                            "Management Fee Applied":"OFST452000",
                            "All in Fee Applied":"OFST452017",
                            "Distribution Fee":"OFST454160",
                            "Ongoing Charges":"OFST452200",
                            "Servicing Fees":"FICA003210",
                            "Conversion Fee":"FICA003211",
                            "Subscription Fee Max":"FICA003212",
                            "Redemption Fee Max":"FICA003213"},
                    "Subscription Redemption Notice Periods":{"Corporate Action Status":"ficad00000",
                                                              "If modification id":"fica000007",
                                                              "Corporate Action Date":"ficad00001",
                                                              "Scope Affected":"fica000001",
                                                              "Identification":"fica000002",
                                                              "Corporate Action Effective Date":"ficad00003",
                                                              "Corporate Action Receipt Date":"fiad00004",
                                                              "Document":"fica000005",
                                                              "Redemption Notice Period":"OFST425550"},
                    "Settlement Data":{"Corporate Action Status":"ficad00000",
                                       "If modification id":"fica000007",
                                       "Corporate Action Date":"ficad00001",
                                       "Scope Affected":"fica000001",
                                       "Identification":"fica000002",
                                       "Corporate Action Effective Date":"ficad00003",
                                       "Corporate Action Receipt Date":"fiad00004",
                                       "Document":"fica000005",
                                       "Fund Valuation Point":"OFST010250",
                                       "Valuation Frequency":"OFST020300",
                                       "Max Number of Possible Decimals Shares":"OFST402500",
                                       "Max Number of Possible Decimals Amounts":"OFST402550",
                                       "Max Number of Possible Decimals NAV":"OFST402600",
                                       "Cut off time for Subscription":"OFST410100",
                                       "Cut off time":"OFST430100",
                                       "Calendar or business days for transactions":"OFST430200",
                                       "Settlement Period for Subscription":"OFST410700",
                                       "Settlement Period for Redemption":"OFST430150",
                                       "Non Dealing Days":"FICA00705099",
                                       "NAV Displacement days":"OFST410060",
                                       "Time Zone For Cut-off":"OFST410090"},
                    "General Meeting":{"Corporate Action Status":"ficad00000",
                                       "If modification id":"fica000007",
                                       "Corporate Action Date":"ficad00001",
                                       "Scope Affected":"fica000001",
                                       "Identification":"fica000002",
                                       "Corporate Action Effective Date":"ficad00003",
                                       "Corporate Action Receipt Date":"fiad00004",
                                       "Document":"fica000005",
                                       "General Meeting Points":"FICA003020",
                                       "General Meeting Date":"FICA003030",
                                       "Extraordinay general meeting date":"FICA003031",
                                       "Reply expected":"FICA000006"},
                    "Mergers":{"Corporate Action Status":"ficad00000",
                               "If modification id":"fica000007",
                               "Corporate Action Date":"ficad00001",
                               "Scope Affected":"fica000001",
                               "Identification":"fica000002",
                               "Corporate Action Effective Date":"ficad00003",
                               "Corporate Action Receipt Date":"fiad00004",
                               "Document":"fica000005",
                               "ISIN_Merger_Fund_Absorbing":"FICA001090",
                               "ISIN_Merged_Fund_absorbed":"FICA001070",
                               "LEI Merge absorbed":"FICA001030",
                               "LEI Merge absorbing":"FICA001040",
                               "Last_trade_Date_absorbing Fund":"FICA001091",
                               "Last_trade_Date_absorbed Fund":"FICA001071",
                               "Last Day for redemption before Merge or Liquidation":"FICA007010",
                               "MergerTaxExempt":"FICA001080",
                               "Umbrella LEI Merge absorbing":"FICA001060",
                               "Umbrella LEI Merge absorbed":"FICA001050"},
                    "Guarantor":{"Corporate Action Status":"ficad00000",
                                 "If modification id":"fica000007",
                                 "Corporate Action Date":"ficad00001",
                                 "Scope Affected":"fica000001",
                                 "Identification":"fica000002",
                                 "Corporate Action Effective Date":"ficad00003",
                                 "Corporate Action Receipt Date":"fiad00004",
                                 "Document":"fica000005",
                                 "Fund Guarantor":"OFST001050",
                                 "Guarantor Rating Review":"FICA002810"},
                    "Investment Policy":{"Corporate Action Status":"ficad00000",
                                         "If modification id":"fica000007",
                                         "Corporate Action Date":"ficad00001",
                                         "Scope Affected":"fica000001",
                                         "Identification":"fica000002",
                                         "Corporate Action Effective Date":"ficad00003",
                                         "Corporate Action Receipt Date":"fiad00004",
                                         "Document":"fica000005",
                                         "Investment Objective":"OFST010300",
                                         "Max Leverage in Fund":"OFST010635",
                                         "Is Fund Targeting Environmental or Social Objectives (EOS)":"OFST010680",
                                         "Swap Counterparty Name":"OFST011110",
                                         "Investment Policy":"FICA000010"},
                    "Other Corporate Actions":{"Corporate Action Status":"ficad00000",
                                               "If modification id":"fica000007",
                                               "Corporate Action Date":"ficad00001",
                                               "Scope Affected":"fica000001",
                                               "Identification":"fica000002",
                                               "Corporate Action Effective Date":"ficad00003",
                                               "Corporate Action Receipt Date":"fiad00004",
                                               "Document":"fica000005",
                                               "Free Text":"FICA004020"},
                    "Taxation and Register":{"Corporate Action Status":"ficad00000",
                                             "If modification id":"fica000007",
                                             "Corporate Action Date":"ficad00001",
                                             "Scope Affected":"fica000001",
                                             "Identification":"fica000002",
                                             "Corporate Action Effective Date":"ficad00003",
                                             "Corporate Action Receipt Date":"fiad00004",
                                             "Document":"fica000005",
                                             "Is Eligible for tax deferred Fund switch in Spain":"OFST808100",
                                             "Number of Shareholders":"FICA002070",
                                             "PEA Plan dEpargne in actions":"OFST808500",
                                             "Other Tax Figures":"FICA002210",
                                             "NAV disclosed channel":"FICA002310"},
                    "Public Periodical Information":{"Corporate Action Status":"ficad00000",
                                                     "If modification id":"fica000007",
                                                     "Corporate Action Date":"ficad00001",
                                                     "Scope Affected":"fica000001",
                                                     "Identification":"fica000002",
                                                     "Corporate Action Effective Date":"ficad00003",
                                                     "Corporate Action Receipt Date":"fiad00004",
                                                     "Document":"fica000005",
                                                     "Country Registration":"FICA61200",
                                                     "Country Deregistration":"FICA61201",
                                                     "New KIID Date":"FICA002080",
                                                     "New Prospectus Date":"FICA002090",
                                                     "NewAnualReport":"FICA002100",
                                                     "New Prospectus Supplement Date":"FICA002111",
                                                     "New SemiAnnual Report Date":"FICA002112"},
                    "CNMV C.A. defined":{"Corporate Action Status":"ficad00000",
                                                     "If modification id":"fica000007",
                                                     "Corporate Action Date":"ficad00001",
                                                     "Scope Affected":"fica000001",
                                                     "Identification":"fica000002",
                                                     "Corporate Action Effective Date":"ficad00003",
                                                     "Corporate Action Receipt Date":"fiad00004",
                                                     "Document":"fica000005",
                                                     "Business Day Calendar":"FICA002410",
                                                     "Fund Leverage over 5%":"FICA002610",
                                                     "De-listing of a Stock Exchange":"FICA002910",
                                                     "Significant Asset reduction":"FICA002510",
                                                     "Suspension of operations":"FICA002710",
                                                     "Beat the pre-defined payoff":"FICA003110"},
                    "Partial Liquidation":{"Corporate Action Status":"ficad00000",
                                           "If modification id":"fica000007",
                                           "Corporate Action Date":"ficad00001",
                                           "Scope Affected":"fica000001",
                                           "Identification":"fica000002",
                                           "Corporate Action Effective Date":"ficad00003",
                                           "Corporate Action Receipt Date":"fiad00004",
                                           "Document":"fica000005",
                                           "Partial Liquidation":"FICA005410"},
                    "Target Market":{"Corporate Action Status":"ficad00000",
                                     "If modification id":"fica000007",
                                     "Corporate Action Date":"ficad00001",
                                     "Scope Affected":"fica000001",
                                     "Identification":"fica000002",
                                     "Corporate Action Effective Date":"ficad00003",
                                     "Corporate Action Receipt Date":"fiad00004",
                                     "Document":"fica000005",
                                     "EMT Client Type Retail":"OFEM010100",
                                     "EMT Professional Investor Type":"OFEM010200",
                                     "EMT Is Investor Type Eligible Counterparty":"OFEM010300"},
                    "Total Liquidation":{"Corporate Action Status":"ficad00000",
                                         "If modification id":"fica000007",
                                         "Corporate Action Date":"ficad00001",
                                         "Scope Affected":"fica000001",
                                         "Identification":"fica000002",
                                         "Corporate Action Effective Date":"ficad00003",
                                         "Corporate Action Receipt Date":"fiad00004",
                                         "Document":"fica000005",
                                         "Total liquidation":"FICA006020"},
                    "Distribution Policy":{"Corporate Action Status":"ficad00000",
                                           "If modification id":"fica000007",
                                           "Corporate Action Date":"ficad00001",
                                           "Scope Affected":"fica000001",
                                           "Identification":"fica000002",
                                           "Corporate Action Effective Date":"ficad00003",
                                           "Corporate Action Receipt Date":"fiad00004",
                                           "Document":"fica000005",
                                           "Share Class Distribution Policy":"OFST020400"},
                    "Risk":{"Corporate Action Status":"ficad00000",
                            "If modification id":"fica000007",
                            "Corporate Action Date":"ficad00001",
                            "Scope Affected":"fica000001",
                            "Identification":"fica000002",
                            "Corporate Action Effective Date":"ficad00003",
                            "Corporate Action Receipt Date":"fiad00004",
                            "Document":"fica000005",
                            "EMT PRIIP Summary Risk Indicator":"OFEM040100",
                            "VAR Policy":"FICA000020"},
                    "Benchmark Index":{"Corporate Action Status":"ficad00000",
                                       "If modification id":"fica000007",
                                       "Corporate Action Date":"ficad00001",
                                       "Scope Affected":"fica000001",
                                       "Identification":"fica000002",
                                       "Corporate Action Effective Date":"ficad00003",
                                       "Corporate Action Receipt Date":"fiad00004",
                                       "Document":"fica000005",
                                       "Benchmark":"OFST023200"},
                    "Implementation Swing Price / Antidilution measures":{"Corporate Action Status":"ficad00000",
                                                                          "If modification id":"fica000007",
                                                                          "Corporate Action Date":"ficad00001",
                                                                          "Scope Affected":"fica000001",
                                                                          "Identification":"fica000002",
                                                                          "Corporate Action Effective Date":"ficad00003",
                                                                          "Corporate Action Receipt Date":"fiad00004",
                                                                          "Document":"fica000005",
                                                                          "Single Pricing Type":"OFST401003",
                                                                          "Anti Dilution measures":"FICA007060"}
                    }
